# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Always use package style import
    always_use_package_imports: true

    # Always declare return types for functions and methods.
    always_declare_return_types: true

    # Ensure that Stream subscriptions are canceled properly.
    cancel_subscriptions: true

    # Ensure that StreamController sinks are closed properly.
    close_sinks: true

    # Ensure that all comment references are valid.
    comment_references: true

    # Enforce having only one member in abstract classes.
    one_member_abstracts: true

    # Allow only throwing Error objects, not Exception or any other type.
    only_throw_errors: true

    # Prefer using 'final' for loop variables in 'forEach' loops.
    prefer_final_in_for_each: true

    # Prefer using single quotes for string literals.
    prefer_single_quotes: true

    # Specify the maximum line length
    lines_longer_than_20_chars: true

    # Enforce an indent of 2 spaces
    indentation: 2

analyzer:
  exclude:
    - lib/main_development.dart
    - lib/main_production.dart
    - lib/main_cubit_observer.dart
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

