name: Hangman

on:
  push:
    branches:
      - main
      - dev
      - stag
  pull_request:
    branches:
      - main
      - dev
      - stag

env:
  FLUTTER_VERSION: 3.0.0

jobs:
  format-lint:
    if: "!github.event.pull_request.draft"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: ":os:-modules-:hash:"
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Formatting
        run: dart format --set-exit-if-changed lib

      - name: Lint
        run: flutter analyze lib
