name: Hangman

on:
  push:
    branches:
      - main
      - dev
      - stag
  pull_request:
    branches:
      - main
      - dev
      - stag

jobs:
  format-lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Dart SDK
        uses: subosito/flutter-action@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: ":os:-modules-:hash:"
          channel: "stable"

      - name: Formatting
        run: dart format lib

      - name: Lint
        run: flutter analyze lib
